# Generated by Django 3.0.6 on 2020-06-01 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiting',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_movie.Movie', verbose_name='Фильм'),
        ),
    ]
